[default.extend-words]
ND = "ND"
Cachable = "Cachable"
# Additional SciML terms
setp = "setp"
getp = "getp"
indexin = "indexin"
ists = "ists"
ispcs = "ispcs"
eqs = "eqs"
rhs = "rhs"
MTK = "MTK"
siz = "siz"
# Legacy identifiers with typos (cannot rename without breaking API)
Incompatability = "Incompatability"
INCOMPATABILITY = "INCOMPATABILITY"